### PR TITLE
[pt] updating typos and small fixes

### PR DESCRIPTION
**Pull request by jpyperez**

### CODE REVIEW

**Comment by jpyperez** [comment]
Hello @VitalikL , once it's merged, do we need to do something to reflect in the lesson?
When I choose NVI version, the typos still there .-.

**Comment by VitalikL** [comment]
Hi @jpyperez . Usually its after the next lesson deploy, however due to caching it might require opening the lesson second time with the internet connection for the cache to be updated.

**Comment by jpyperez** [comment]
@VitalikL , I checked today and the NVI version still the old one (I've opened web version, and it's the old one as well) .-.
Can I do something to check it better? (https://sabbath-school.adventech.io/pt/2024-01/09/03-monday-o-messias-sofredor)

**Comment by jpyperez** [comment]
Updating: Now the new version of NVI is there. Thank you so much

**Comment by VitalikL** [comment]
Yes, basically the lesson deployment was not initiated until recently.

**Pull request merged**
